import '@/styles/globals.css'
// import 'simpledotcss/simple.min.css'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalProviders from '@/providers/globalProviders'
import Header from '@/components/shared/header'
import SharedComponents from '@/components/shared'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Qutool 🦾',
    default: 'Qutool 🦾'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={inter.className}>
        <GlobalProviders>
          <SharedComponents />
          {children}
        </GlobalProviders>
      </body>
    </html>
  )
}
